
export enum VALID_ARGS {
  BOOTSTRAP = 'BOOTSTRAP',
  DIRSTAT = 'DIRSTAT',
  REMOVE_DEPENDENCIES = 'REMOVE_DEPENDENCIES',
  INSTALL_DEPENDENCIES = 'INSTALL_DEPENDENCIES',
  DEfAULT_DIR = 'DEfAULT_DIR',
}

export const NODE_PACKAGE_FILENAME = 'package.json';
