
export enum VALID_ARGS {
  BOOTSTRAP = 'BOOTSTRAP',
  REMOVE_DEPENDENCIES = 'REMOVE_DEPENDENCIES',
  INSTALL_DEPENDENCIES = 'INSTALL_DEPENDENCIES',
  GLOBAL_DIR = 'GLOBAL_DIR',
}

export const NODE_PACKAGE_FILENAME = 'package.json';
